import os
import warnings
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

LEV_CI = os.getenv("CROWDIN_TOKEN")
LEV_CI_PID = os.getenv("CROWDIN_LEVANTE_PID")

LEV_AT_PAT = os.getenv("LEVANTE_AT_PAT")
LEV_AT_BASE = os.getenv("LEVANTE_AT_BASEID")
LEV_AT_SSTABLE = os.getenv("LEVANTE_AT_STRINGSTABLE")
LEV_AT_CORPUSTABLE = os.getenv("LEVANTE_CORPUSTABLE")

AT_TRACKER = os.getenv("AT_TRANSLATIONTRACKER")
AT_TRACKER_BASE = os.getenv("AT_TRACKER_BASE")
AT_IB_DIFFTABLE = os.getenv("AT_IB_DIFFTABLE")
AT_SURVEY_DIFFTABLE =  os.getenv("AT_SURVEY_DIFFTABLE")
AT_TRANSL_REVTABLE = os.getenv("AT_TRANSLATIONS_TABLE")

CROWDIN_TEST = os.getenv("CROWDIN_TESTTOKEN")
CROWDIN_TESTPID = os.getenv("CROWDIN_TESTPID")

# Resolve the credentials path if it's relative
GOOGLE_APPLICATION_CREDENTIALS_JSON_DEV = os.getenv("GOOGLE_APPLICATION_CREDENTIALS_JSON_DEV")

# Local dev: use GOOGLE_APPLICATION_CREDENTIALS_DEV from .env (absolute path recommended).
# CI/GHA can set GOOGLE_APPLICATION_CREDENTIALS or use secrets later.

GOOGLE_APPLICATION_CREDENTIALS_DEV = os.getenv("GOOGLE_APPLICATION_CREDENTIALS_DEV")
if GOOGLE_APPLICATION_CREDENTIALS_DEV:
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_APPLICATION_CREDENTIALS_DEV
# Warn on missing env vars; callers that need a var will fail at use. Allows workflows to pass only the subset they need.
_ENV_VARS = {
    "CROWDIN_TOKEN": LEV_CI,
    "CROWDIN_LEVANTE_PID": LEV_CI_PID,
    "LEVANTE_AT_PAT": LEV_AT_PAT,
    "LEVANTE_AT_BASEID": LEV_AT_BASE,
    "LEVANTE_AT_STRINGSTABLE": LEV_AT_SSTABLE,
    "LEVANTE_CORPUSTABLE": LEV_AT_CORPUSTABLE,
    "AT_TRANSLATIONTRACKER": AT_TRACKER,
    "AT_TRACKER_BASE": AT_TRACKER_BASE,
    "AT_IB_DIFFTABLE": AT_IB_DIFFTABLE,
    "AT_SURVEY_DIFFTABLE": AT_SURVEY_DIFFTABLE,
    "AT_TRANSLATIONS_TABLE": AT_TRANSL_REVTABLE,
    "CROWDIN_TESTTOKEN": CROWDIN_TEST,
    "CROWDIN_TESTPID": CROWDIN_TESTPID,
    "GOOGLE_APPLICATION_CREDENTIALS": os.getenv("GOOGLE_APPLICATION_CREDENTIALS"),
    "GOOGLE_APPLICATION_CREDENTIALS_DEV": GOOGLE_APPLICATION_CREDENTIALS_DEV,
}
for name, value in _ENV_VARS.items():
    if not value:
        warnings.warn(f"Missing environment variable: {name}. Some endpoints may fail.", UserWarning, stacklevel=0)
